### ISSUE TITLE
Update structopt documentation, examples and crate

### ISSUE THREAD

**Issue by gameldar** [rust-cli/paw#8]
With structopt 0.2.17 paw is now supported through the 'paw' feature meaning that paw and structopt can be used just by including both in the dependencies:

```toml
[dependencies]
structopt = { version = "0.2.17", features = [ "paw" ] }
paw = "1.0"
```

The documentation and examples need updating and the paw-structopt crate can be deprecated.
